### ISSUE TITLE
Filtering the data using PID

### ISSUE THREAD

**Issue by roeyzeldin11** [alban/fsnotify-enricher#2]
Currently when using the enricher, I get data on inotify watchers which my process did not create.
Using the WD to filter is not completely viable, since WD are not unique on the host, but for an inotify fd.

If the gadget could filter event only on the process that started it, or as a parameter to pass to it, it would be helpful.

Thanks

**Comment by alban** [comment]
It should be possible with the [tracer-pid parameter](https://github.com/alban/fsnotify-enricher/blob/ffd7ce54fb236193494e05539b803716c24f8af4/gadget.yaml#L137-L140):
```
sudo -E ig run ghcr.io/alban/fsnotify-enricher:latest --tracer-pid=42
```

**Comment by roeyzeldin11** [comment]
Awesome, marking as Closed
