### ISSUE TITLE
Getting the Inode of an event

### ISSUE THREAD

**Issue by roeyzeldin11** [alban/fsnotify-enricher#3]
Our team would like to get the Inode the evet happened against, getting it for delete events seems to be difficult, is there a way to get the data from the gadget?
Thanks

**Comment by alban** [comment]
It should be possible: the gadget already has a kprobe on `inotify_handle_inode_event` and this function is given the inodes of the file being accessed and its directory:

```
int inotify_handle_inode_event(struct fsnotify_mark *inode_mark, u32 mask,
                               struct inode *inode, struct inode *dir,
                               const struct qstr *name, u32 cookie)
```
